use std::error::Error;
use y2015::day1;

fn main() -> Result<(), Box<dyn Error>> {
    day1::execute();

    Ok(())
}